### ISSUE TITLE
Remove me

### ISSUE THREAD

**Issue by No1129** [QuiltMC/quiltmc.org#134]
I don't want to be tied with this shit
and y- who cares just remove me form the shit

**Comment by No1129** [comment]
and remove me form the logs

**Comment by gdude2002** [comment]
Hi - I don't believe you have any involvement with this repo, so I'll just close this issue. Please contact the relevant project or team with specific info on what you want.

**Comment by No1129** [comment]
https://github.com/QuiltMC/quiltmc.org/blob/main/public/assets/img/statement-evidences/dea6970d-7146-4a7d-99cd-1b6e0f5d9121.png

**Comment by No1129** [comment]
this

**Comment by No1129** [comment]
remove this

**Comment by gdude2002** [comment]
No, absolutely not.
