### ISSUE TITLE
why

### ISSUE THREAD

**Issue by No1129** [QuiltMC/quiltmc.org#135]
No, absolutely not.

_Originally posted by @gdude2002 in https://github.com/QuiltMC/quiltmc.org/issues/134#issuecomment-1550141058_
            why
            just remove the img

**Comment by No1129** [comment]
why is this so hard

**Comment by gdude2002** [comment]
Your name has been redacted, so we have no reason to do so. We will not compromise our work in this instance.

If this is an issue you run into frequently, perhaps you should interact with people more conscientiously.
