### ISSUE TITLE
Typo in new community guidelines

### ISSUE THREAD

**Issue by woodiertexas** [QuiltMC/quiltmc.org#139]
In https://preview-125.quiltmc-org.pages.dev/en/community/guidelines/#staff-activity-requirements, the sentence about dormant accounts is written as `...be caused by leaving dormant account with that level of access`.

It should be `be caused by leaving any dormant accounts with that level of access`.

**Comment by Akarys42** [comment]
Done in 5ba1a1470cf29b5c69d0589f0fa2fc401b243c5299b52088cea061a7db833a2e
