### ISSUE TITLE
Modrinth launcher not on install page

### ISSUE THREAD

**Issue by MOULINIER** [QuiltMC/quiltmc.org#148]
Hi !
I just wanted to bring the fact that the Modrinth launcher (that just launched) isn't mentioned here, even if there is quilt as an option to create an instance
![image](https://github.com/QuiltMC/quiltmc.org/assets/94763673/dfa46d1a-7be0-4596-be66-c5c5d37fd387)

(Sorry if this issue is not in the right place / Not useful, I am "new" to github) !

**Comment by obj-obj** [comment]
Don't worry, this is the right place
