### ISSUE TITLE
team listings page has two "member not found" errors on it

### ISSUE THREAD

**Issue by ix0rai** [QuiltMC/quiltmc.org#157]
in both the Mappings team and the Events team, there are cards for members that no longer exist in Quilt.
![a "member not found" card](https://media.discordapp.net/attachments/1103986836415713300/1152771157544673392/image.png?width=622&height=618)

**Comment by Southpaw1496** [comment]
The first one was Iota, who changed their GitHub username from MartrixX. I pushed a commit to fix . 

The second is Redblueflame, who I removed from the team data before he was removed from the GitHub team. He was removed last night (my time), so the rebuilding from the commits I pushed this morning has fixed that too.
