### ISSUE TITLE
The forum button leads to 404 page

### ISSUE THREAD

**Issue by Niterux** [QuiltMC/quiltmc.org#181]
This include the mod incompatibility megathread

https://github.com/QuiltMC/quiltmc.org/assets/110568869/c00418d9-b648-47c1-ae6a-f7edbdaa47a5

https://forum.quiltmc.org/t/mod-incompatibility-megathread/261

**Comment by ix0rai** [comment]
hi! this has been an issue for a while, and we're working on it. some of the hardware running the forum developed issues (as far as I know, a hard drive failed), and the infrastructure team is working to resolve that and bring everything back up.

**Comment by OroArmor** [comment]
Fixed as of today!
