### ISSUE TITLE
FAQ Looks Bad In Firefox

### ISSUE THREAD

**Issue by CoolMineman** [QuiltMC/quiltmc.org#19]
![image](https://user-images.githubusercontent.com/62723322/116770422-7cca6a80-aa09-11eb-9b69-f88a3d1f8ce5.png)

**Comment by TheEpicBlock** [comment]
What Firefox version are you using? I'm running 87.0 and it is looking completely normal.
<details>
<summary>Screenshot</summary>
<img src="https://user-images.githubusercontent.com/61842090/116781111-1da83c80-aa81-11eb-8491-485dc03e0118.png">
<img src="https://user-images.githubusercontent.com/61842090/116781169-927b7680-aa81-11eb-8bb3-0147b94e3bc6.png">
</details>

**Comment by Leo40Git** [comment]
Dark Reader causes this error. Disable it for quiltmc.org - it's already semi-dark anyway :P

**Comment by gdude2002** [comment]
I've double-checked and yep, this is a dark reader problem. Site's already dark-mode - toggle it off and see what you think!
