### ISSUE TITLE
order changelogs based on semver

### ISSUE THREAD

**Issue by ix0rai** [QuiltMC/quiltmc.org#191]
on https://quiltmc.org/en/changelog/, versions are ordered based on the parsed markdown files instead of being ordered based on their semver number

**Comment by simpledemonn** [comment]
That was on purpose, it is imo more flexible that way. The project can order them as the devs think is right, even if it doesn't follow sem/flexver.

**Comment by ix0rai** [comment]
we could define the strategy per-project

**Comment by simpledemonn** [comment]
I'm honestly not a fan of hardcoding that, although I guess it could be a custom property as well. What case do you forsee where sorting the versions would actually change the order in a way that cannot be done in the original file?

**Comment by ix0rai** [comment]
I don't, I think it's more ergonomic to append new versions to the bottom of a changelog file instead of the top

**Comment by ix0rai** [comment]
although yeah, it's kinda pointless. I'll manually fix my ordering
