### ISSUE TITLE
Youtube-dl and utility mods are not piracy or illegal

### ISSUE THREAD

**Issue by AcaiBerii** [QuiltMC/quiltmc.org#21]
Youtube-dl allows you to download already publicly available videos and metadata from streaming services. It is not piracy no matter what Youtube wants you to think it is.

Hacked clients are encouraged by many servers and are legal if they do not violate federal law. Many do not as they don't allow or have modules for acts that would violate laws.

I suggest you change these rules imo lole.

**Comment by TelepathicGrunt** [comment]
> Hacked clients are encouraged by many servers and are legal

this is extremely false and I would encourage you to reread mojang’s eula. If you are using a hacked client, please do not do so and actually buy Minecraft to support Mojang. And report the servers that are encouraging hacked clients as if I recall, similar servers were shut down for that

**Comment by Forkk** [comment]
I'm not a lawyer, but I'm fairly sure using `youtube-dl` on videos under the standard YouTube license does violate that license. Regardless, it violates YouTube's EULA as well, which is also against our rules.

Nowhere in the rules does it say that hacked clients are illegal, but they do violate Discord's EULA. The rules disallow anything that is either illegal, *or* in violation of the EULA of Mojang, Discord, etc.

In the future, I suggest you find a more productive way to voice your concerns on this matter.
