### ISSUE TITLE
Switch icon set

### ISSUE THREAD

**Issue by gdude2002** [QuiltMC/quiltmc.org#225]
I've reviewed my Font Awesome Pro usage and finances, and deduced the following:

- My Font Awesome Pro licence expires on June 3rd
- Quilt is the only project/site using any kits under my account
- I am unable to afford the renewal cost

As a result, Quilt will need to move from the Font Awesome kit on my account.

Here are some alternative approaches:
- **Recommended:** Switch to [Iconify](https://iconify.design/) via its JS libraries (or a compatible component library)
- Switch to Font Awesome's free offering, and switch away from the custom/premium icons currently used
- Pay for Font Awesome yourselves, and switch to your own kit

Sorry, y'all - times are tough lately.

**Comment by Southpaw1496** [comment]
Switching to the free version of Font Awesome isn't an option. It has a limit of 10k views in a month, and we've exceeded that in the past 72 hours alone, according to Cloudflare.

For reference, the Pro plan is $99/year. There is a Pro Lite plan for $49/year, but its limit is 100k/month, which we could conceivably hit: We've had over 10k views in three days, so we could conceivably have over 100k in 30.

I will investigate switching to Iconify, but it looks like a lot of work. If the libraries are even compatible with the ancient version of Astro that we're using.

**Comment by Southpaw1496** [comment]
The good news is that switching to Iconify seems relatively straightforward.

The *bad* news is that to do so in a future-proof way seems to require updating to a modern version of Astro, which requires gutting the i18n system and rebuilding it from scratch. I tried starting it last year and gave up, but perhaps I'm a slightly better JavaScript developer now.

**Comment by Pyrofab** [comment]
As a note, updating Astro would also benefit #232. Unfortunately I don't have specific Astro knowledge, but if you pushed a draft PR with your first batch of changes I think I could contribute a bit.

**Comment by Southpaw1496** [comment]
An update if you haven't been keeping up with Discord:

I have managed to get the existing i18n stack running on Astro 4.13, and it seems like the rest of the site has come along for the ride without an issue. There's an enormous amount of work to get the site up-to-scratch with modern Astro best practices, but the site we have still works, so I'm going to focus on getting the icons replaced with Iconify icons using `astro-icons`

**Comment by CelDaemon** [comment]
I was going report the icons not working, but it seems you all are figuring it out already!
Hopefully it isn't too much work trying to make everything function, if it's needed I'd be willing to help out.

**Comment by Southpaw1496** [comment]
I've started the Teams page today and it's been relatively painless. Apart from CSS playing its usual tricks.
<img width="823" alt="Screenshot 2024-08-12 at 3 28 30 PM" src="https://github.com/user-attachments/assets/727984ac-df72-4725-b76b-fee13c86973b">
