### ISSUE TITLE
How to determine latest mappings version as a bot?

### ISSUE THREAD

**Issue by mk-pmb** [QuiltMC/quiltmc.org#229]
Hi! How can I determine the latest version? In the Readme (of the [quilt-mappings repo](https://github.com/QuiltMC/quilt-mappings), where I originally posted this issue) I found the hint

> You can see additional information and see what the latest QM build for each Minecraft version is with [LambdAurora's import tool](https://lambdaurora.dev/tools/import_quilt.html).

… which redirected me to https://quiltmc.org/en/usage/latest-versions/ , but the site uses CloudFlare protection in very paranoid mode that doesn't even allow me read access. (According to CloudFlare, due to my privacy preferences, I'm not "human" enough.)
So, is there a way for bots like me to automatically determine the latest version?

Edit: I managed to enlist a CloudFlare-certified human for help but they said the page was broken anyway.

**Comment by UpcraftLP** [comment]
> Edit: I managed to enlist a CloudFlare-certified human for help but they said the page was broken anyway.

Seems fine to me, what is "broken" about it?
<br>
![image](https://github.com/QuiltMC/quiltmc.org/assets/10714589/5d93c7cf-9894-46e4-8de7-6cfb1562f43c)

**Comment by mk-pmb** [comment]
@FirstMegaGame4
That works. Thanks! I'll file a docs PR to have the Readme mention this option.

@UpcraftLP
For me, the website has no useful content. It only shows "Enable JavaScript and cookies to continue" – which is forbidden by the privacy configuration for this task. Old lab notes say that it would be useless anyway because I would fail their captcha.

**Comment by Akarys42** [comment]
The raw data of https://quiltmc.org/en/usage/latest-versions/ is also available at https://quiltmc.org/api

**Comment by mk-pmb** [comment]
Thanks for this link, it may be informative for others. Currently, however, it suffers from the same Cloudflare paranoia as the original link, for me showing only "Enable JavaScript and cookies to continue".

**Comment by Akarys42** [comment]
That sounds likely. The infra team has to make a special rule to relax the cloudflare restriction on the API endpoints. I guess they weren't tested outside of an actual broswer. That being said, I believe it is called by some launchers or so, to get the latest installer.

**Comment by Pyrofab** [comment]
Just checked, there is already a rule in place to set the Cloudflare security to the "essentially off" setting. My guess is that the VPN/TOR exit node you are going through has such a horrendous web reputation that even Cloudflare's lowest setting doesn't let you through without a JS check. I don't think we can reasonably lower it further on our end, so you may have to either change your VPN configuration or enable Javascript for this website.

**Comment by mk-pmb** [comment]
> I don't think we can reasonably lower it further on our end,

What risk do you fear from mere read access?

**Comment by Akarys42** [comment]
That seems overly complex for nothing. Can't someone with Cloudflare access check why the access is being rejected? I also made a worker to post firewall alerts periodically to a channel, but I don't think it has been restored sadly ([my poor baby](https://github.com/QuiltMC/workers/tree/main/firewall-event-checker)).

**Comment by Akarys42** [comment]
Ideally the team needs to find out why you're getting blocked. Are you in
China by any chance, or using a VPN or Tor? They have a big IP reputation
issue. This firewall shouldn't be hit by anyone who isn't an active
nuisance on the infrastructure. As for modifying the message, it requires a
very expensive Cloudflare subscription to do so. Can you please screenshot
what you see when manually navigating to the endpoint in your browser
and/or curl?

**Comment by mk-pmb** [comment]
> As for modifying the message, it requires a very expensive Cloudflare subscription to do so.

Cool, I learned something today. It fits the overall picture.

> Ideally the team needs to find out why you're getting blocked.

Because I'm not ["human"](https://youtu.be/fsF7enQY8uI) enough, obviously. (Hammering this point because as a privacy activist I hate the lie that user agent reputation is about humanness.)
Yes I was using TOR, as Pyrofab already guessed. It's a known problem with Cloudflare that they are quick to insult people as subhuman because they use a [lazy-hostile IP repuration mechanism and prefer using bad science for victim blaming](https://blog.torproject.org/trouble-cloudflare/) rather than fixing their software. All other major CDNs don't have that problem. It fits with their aggressive marketing approach that also is not primarily optimized for factual correctness.

For an API, that humanness-lie is even more ridiculous obviously. Of course for a project like this, there's probably just not enough money to pay a serious CDN, but then people should at least know the implications of their choices.
If the issue were still a problem, I'd even try and help you find a solution that works without CloudFlare, e.g. maybe finding ways to host on GitHub pages instead.
Which would of course depend on what the actual fear scenario is (question above still unanswered or I missed it), and whether the API provides extra data over what is available from unrestricted sources (question above still unanswered or I missed it).
My personal use case currently seems to work sufficiently without the API, so I don't see a need for technical change, just for more awareness.

**Comment by Akarys42** [comment]
Back when I was in charge, I took the decision to officially drop support
for Tor communication, due to the risks provided with bypassing any
protection coming from such a network, sorry. It'll be up to the current
team to decide to uphold this or not.

The decision to move to Cloudflare was a long and involved process, and I
do not see a universe where switching back is a good idea. A large part of
the infrastructure even uses Cloudflare exclusive features to work, which
are provided entirely for free, something no other CDN will do.

**Comment by Pyrofab** [comment]
As an occasional Tor user myself, I agree that this state of affairs is rather unfortunate. And depending on Cloudflare's mood, I guess the JS challenge may not even work...
However, as the other person said, Cloudflare is convenient for us, and unfortunately the simplest ways to mitigate your issues (disabling the security/changing the message) are paywalled. If someone has a good idea that is easy and cheap to implement I can try it, but my free time on this project is limited so I can't promise anything.
