### ISSUE TITLE
"open an issue on GitHub" in code of conduct has wrong link

### ISSUE THREAD

**Issue by weeping-shadow** [QuiltMC/quiltmc.org#23]
At the bottom of the Code of Conduct there is a link that is supposed to go to https://github.com/QuiltMC/quiltmc.org/issues but links to https://github.com/QuiltMC/quiltmc.orgissues instead. This isn't much of an issue but might be worth mentioning

**Comment by weeping-shadow** [comment]
![Screenshot_2021-07-04_22-28-00](https://user-images.githubusercontent.com/62074054/124399976-20d8d680-dd17-11eb-9509-5b36b7c48f94.png)

**Comment by gdude2002** [comment]
Thanks for the heads up, I've fixed it!
