### ISSUE TITLE
[Suggestion] Softer white for light theme

### ISSUE THREAD

**Issue by KJP12** [QuiltMC/quiltmc.org#28]
As suggested by @kvverti in Quilt Community's [#quilt-discussion](https://canary.discord.com/channels/817576132726620200/833939559636271105/948014704599662603)

## Reasons
- Pure white can be quite harsh on the eyes when used excessively.
- Windows 95 through Windows 7  didn't use pure white in most of the UI elements outside of Internet Explorer and File Explorer.

**Comment by gdude2002** [comment]
I'm about to look into this, but have y'all used Google or GitHub lately?

**Comment by gdude2002** [comment]
Alright, I created #30 - please take a look at [the preview](https://deploy-preview-30--ecstatic-booth-88897a.netlify.app) and see what you think.

**Comment by KJP12** [comment]
> I'm about to look into this, but have y'all used Google or GitHub lately?

Haven't used light theme with either in a while, so, wouldn't be fair for me to say much there.

Does still seem about as white as it can be to me however, even comparing it to Google in Firefox.

**Comment by gdude2002** [comment]
GitHub and Google both use `#FFFFFF`, yeah - that's why I was surprised, haha

Either way, feel free to leave a comment on the PR if you'd like, I've pinged Thalia on Discord as well.
