### ISSUE TITLE
Astro?

### ISSUE THREAD

**Issue by obj-obj** [QuiltMC/quiltmc.org#35]
https://astro.build seems cool, might try refactoring this site using it if there's any benefits

Edit: PR at #58

**Comment by gdude2002** [comment]
Looks interesting for the future maybe, but we have no plans to move away from Jekyll right now - it's just what more of us are familiar with.

**Comment by gdude2002** [comment]
I mean it's clearly also a static site generator so there will be similarities, but the development effort isn't worth spending time on right now

**Comment by obj-obj** [comment]
Yeah it was just an idea, I might try to push it more if it actually seems useful compared to jekyll but for now everything seems pretty similar

**Comment by gdude2002** [comment]
Sooooooo

**Comment by gdude2002** [comment]
We ended up outgrowing Jekyll, so @LeoCTH is currently doing a new port to Astro, with some new site features in mind.

**Comment by obj-obj** [comment]
> We ended up outgrowing Jekyll, so @leocth is currently doing a new port to Astro, with some new site features in mind.

Oh cool, can I help? I know how to do some scuffed HTML minification stuff

**Comment by obj-obj** [comment]
![image](https://user-images.githubusercontent.com/57120300/183313545-e043b65a-6899-45d1-82b6-20828ef88816.png)

**Comment by obj-obj** [comment]
Pog
