### ISSUE TITLE
Add Installer Download page

### ISSUE THREAD

**Issue by TheGlitch76** [QuiltMC/quiltmc.org#40]
I don't have the URLs to give right now, but I need an "install quilt" page on the website with two buttons: Windows x64, Universal.
Some extra space for adding guides for specific launchers (I know PolyMC and ATL are already lined up to add quilt support during the beta) would be nice

**Comment by gdude2002** [comment]
I'll definitely need some URLs, chief - but I think we already have a layout in mind

**Comment by gdude2002** [comment]
We did this. It's not linked on the front page yet, though.
