### ISSUE TITLE
Timeline Out of Date

### ISSUE THREAD

**Issue by sschr15** [QuiltMC/quiltmc.org#41]
The [timeline](https://quiltmc.org/about/timeline/) is currently (roughly) one year out-of-date, and I know that QMC development has happened in the last year...

**Comment by gdude2002** [comment]
What would you have us add to it? I'm at a loss as to what's significant enough

**Comment by futurelucas4502** [comment]
Thought I'd hijack this issue to save creating a new one and say potentially adding that QuiltMC is now in beta would be a good addition

**Comment by Southpaw1496** [comment]
Does anyone have anything more to add, or can this issue be closed?
