### ISSUE TITLE
Console errors caused by the Technic Launcher update script (+ more)

### ISSUE THREAD

**Issue by pluiedev** [QuiltMC/quiltmc.org#66]
Currently, whenever you visit a page that is *not* the Technic Launcher install page, you would get a similar console error to this:
```
Uncaught (in promise) TypeError: e is null
    g https://quiltmc.org/en/:1
```
This is due to the fact that the Technic Launcher update script is currently *incorrectly* bundled and run on every page on the site, and the script obviously fails to find specific elements that only exist in the Technic page.

Now, this is actually a bit of a hard issue to solve, since the fundamental issue doesn't even lie in the fact that we're bundling the wrong script in the wrong pages—the real issue is, the Technic Launcher script should only be run *on the client*; the static site generator can't just look up the latest Technic release and substitute that into the built site, as that would defeat the point entirely.

Thusly, in Astro we must [mark the script as a client-only script](https://docs.astro.build/en/core-concepts/astro-components/#client-side-scripts), which doesn't allow us to use ESM modules within our code. This is feasible with the patch notes viewer due to its simplicity, but with Technic we have about 200 lines of TypeScript combined to do the task—perhaps we would need to precompile the code into client-side friendly JS with something like `rollup` and then directly include it in the built site, but I'm not sure whether that's worth the maintenance costs this extra mechanism takes.

**Comment by obj-obj** [comment]
@pluiedev The issue isn't that we're dong something wrong, the script is only supposed to be loaded on the technic page but an Astro bug is bundling it on every page multiple times as well as duplicating CSS tags

https://github.com/withastro/astro/issues/4295
