### ISSUE TITLE
Add endorsed sponsors to homepage

### ISSUE THREAD

**Issue by Southpaw1496** [QuiltMC/quiltmc.org#68]
While #55 adds an information page with information about all sponsors, Endorsed Sponsors need a section on the homepage, with their logo, a short description of their offerings, and a link to their website.

**Comment by Akarys42** [comment]
Hey @gdude2002, are you working on that one? Don't forget to self assign!

**Comment by gdude2002** [comment]
There's nothing I can do right now without a page to link to, but I was planning on working on it, yeah

**Comment by Southpaw1496** [comment]
Fixed by #110
