### ISSUE TITLE
Edge read aloud breakage

### ISSUE THREAD

**Issue by ghost** [QuiltMC/quiltmc.org#78]
For some reason Edge reads the first ❓ section just fine but when it comes to reading the 🔔 section it's skipped entirely and it just moves onto the `Moving from Tupperbox` heading. Not sure if there is anything that can be tweaked to fix this but thought I'd report it anyway.

https://github.com/QuiltMC/quiltmc.org/blob/9f1e6143c162e7d1c80e6f393b66db0edb8c6282/src/pages/en/community/pluralkit.mdx?plain=1#L28-L32

**Comment by obj-obj** [comment]
It's just a standard list element so I think this would be an edge bug:
![image](https://user-images.githubusercontent.com/57120300/196014169-53712528-9ff0-4815-8efd-b09709b888bb.png)

**Comment by CheaterCodes** [comment]
Can confirm this bug. I have also submitted a report to edge about this.
