### ISSUE TITLE
QSL redirect not working

### ISSUE THREAD

**Issue by LostLuma** [QuiltMC/quiltmc.org#79]
The quilt installer shows a prompt to install QSL after a successful installation, however the link provided (https://quiltmc.org/qsl) 404s instead of redirecting to modrinth as [the source here](https://github.com/QuiltMC/quiltmc.org/blob/stable/src/pages/en/qsl.astro) would imply is the intended behavior.

**Comment by obj-obj** [comment]
@LostLuma lmao it's in the `en` directory which means the redirect is at https://quiltmc.org/en/qsl

**Comment by LostLuma** [comment]
I'm aware why it happens, the installer does not link to the `/en` page though.

**Comment by obj-obj** [comment]
Yeah I just fixed it, it should work now
